#!/bin/sh
#
# Copyright (c) 2007-2011 Red Hat, Inc.
# Distributed under license by Red Hat, Inc. All rights reserved.
# This program is made available under the terms of the
# Eclipse Public License v1.0 which accompanies this distribution,
# and is available at http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     Red Hat, Inc. - initial API and implementation
#
# 
# This script is provided to disble global menu for Ubuntu Unity
# It is workaround for https://issues.jboss.org/browse/JBDS-1781
#

UBUNTU_MENUPROXY=0 $(dirname "$0")/studio/jbdevstudio